[mysqld]
basedir=D:/MySQL/MySQL Server 8.0
datadir=D:/moniC/project/learn/tmp/mysql-course-runtime/data
port=33306
bind-address=127.0.0.1
mysqlx=0
pid-file=D:/moniC/project/learn/tmp/mysql-course-runtime/mysqld.pid
log-error=D:/moniC/project/learn/tmp/mysql-course-runtime/mysqld.log
